##Utilizando a biblioteca NumPy :

In [1]:
import numpy as np


a. Cria um array de números 1 com shape (8, 2) 

In [ ]:
array_ones = np.ones((8, 2))
print('Array de números 1 (shape 8, 2):')
print(array_ones)

Array de números 1 (shape 8, 2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


b. Cria um array de zeros com shape (5, 7)

In [3]:
array_zeros = np.zeros((5, 7))
print("\nArray de zeros (shape 5, 7):")
print(array_zeros)


Array de zeros (shape 5, 7):
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


c. Subtraia o novo array de outro com dados aleatórios e armazene o numa variável chamada subarray 

In [8]:
random_array = np.random.rand(5, 7)
subarray = random_array - array_zeros
print("\nSubarray (random_array - array_zeros):")
print(subarray)


Subarray (random_array - array_zeros):
[[0.71353169 0.71684187 0.1902742  0.53486428 0.93817532 0.29010535
  0.98999843]
 [0.60133564 0.96282334 0.95801245 0.9409528  0.8955125  0.36744941
  0.75396882]
 [0.47859863 0.43132196 0.92104722 0.88885073 0.03269715 0.17639005
  0.98404655]
 [0.81959031 0.6997478  0.19273853 0.92765387 0.0625134  0.48788745
  0.74165686]
 [0.69751918 0.01767941 0.53775453 0.3008563  0.10812103 0.34275179
  0.01437299]]


d. Calcula a média dos valores do array subarray

In [9]:
media_subarray = np.mean(subarray)
print("\nMédia dos valores no subarray:")
print(media_subarray)


Média dos valores no subarray:
0.5633611952886701
